"""
utils/exporters.py — In-memory PDF and DOCX report generation.

Accepts ONLY a normalized export schema (see build_export_schema below).
Never writes to disk. All outputs use BytesIO.
On failure, returns None and logs error — does NOT crash the caller.
"""

import io
import re
import logging
from datetime import datetime
from typing import Optional

logger = logging.getLogger("lumina.exporters")


# ─────────────────────────────────────────────────────────────────────────────
# SCHEMA BUILDER
# ─────────────────────────────────────────────────────────────────────────────

def build_export_schema(
    questions: list,
    answers: dict,
    evaluations: list,
    session_id=None,
) -> dict:
    """
    Normalize raw session state into a portable export schema.
    Keys are sanitized; missing fields default gracefully.
    """
    earned = sum(e.get("score", 0) for e in evaluations)
    max_marks = sum(q.get("marks", 1) for q in questions)
    pct = round((earned / max_marks) * 100, 1) if max_marks else 0.0
    grade = (
        "S" if pct >= 90 else
        "A" if pct >= 80 else
        "B" if pct >= 70 else
        "C" if pct >= 50 else
        "D"
    )

    # Per-type performance breakdown
    type_breakdown: dict = {}
    for i, q in enumerate(questions):
        t = q.get("type", "Unknown")
        ev = evaluations[i] if i < len(evaluations) else {}
        if t not in type_breakdown:
            type_breakdown[t] = {"earned": 0, "max": 0, "count": 0}
        type_breakdown[t]["earned"] += ev.get("score", 0)
        type_breakdown[t]["max"] += q.get("marks", 1)
        type_breakdown[t]["count"] += 1

    normalized_questions = []
    for i, q in enumerate(questions):
        ev = evaluations[i] if i < len(evaluations) else {}
        ans = answers.get(i, "")
        if isinstance(ans, dict):
            ans = str(ans)
        normalized_questions.append({
            "index": i + 1,
            "question": _sanitize(q.get("question", "")),
            "type": _sanitize(q.get("type", "Unknown")),
            "user_answer": _sanitize(str(ans) if ans else "[No answer provided]"),
            "correct_answer": _sanitize(str(q.get("correct_answer", q.get("answer", "N/A")))),
            "score": ev.get("score", 0),
            "max_score": q.get("marks", 1),
            "is_correct": bool(ev.get("is_correct", False)),
            "feedback": _sanitize(ev.get("feedback", "")),
            "hint": _sanitize(ev.get("hint", "")),
            "strengths": _sanitize(ev.get("strengths", "")),
            "weaknesses": _sanitize(ev.get("weaknesses", "")),
            "improvements": _sanitize(ev.get("improvements", "")),
            "criteria_scores": {
                _sanitize(k): v
                for k, v in ev.get("criteria_scores", {}).items()
            },
        })

    return {
        "session_id": str(session_id) if session_id else "N/A",
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "questions": normalized_questions,
        "summary": {
            "total_score": earned,
            "max_score": max_marks,
            "percentage": pct,
            "grade": grade,
            "total_questions": len(questions),
            "correct_count": sum(1 for e in evaluations if e.get("is_correct")),
            "performance_breakdown": type_breakdown,
        },
    }


# ─────────────────────────────────────────────────────────────────────────────
# PDF GENERATION
# ─────────────────────────────────────────────────────────────────────────────

def generate_pdf_report(schema: dict) -> Optional[bytes]:
    """
    Generate a PDF report from a normalized export schema.
    Returns raw bytes on success, None on failure.
    All text is sanitized and truncated to prevent overflow.
    Uses fpdf2 v2.7.x API.
    """
    try:
        from fpdf import FPDF
        from fpdf.enums import XPos, YPos

        class LuminaPDF(FPDF):
            def header(self):
                self.set_font("Helvetica", "B", 10)
                self.set_text_color(120, 80, 200)
                self.cell(0, 8, "Lumina Assessment - Evaluation Report", align="C",
                          new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                self.set_draw_color(80, 50, 140)
                self.set_line_width(0.5)
                self.line(10, self.get_y(), 200, self.get_y())
                self.ln(4)

            def footer(self):
                self.set_y(-12)
                self.set_font("Helvetica", "I", 8)
                self.set_text_color(150, 150, 150)
                self.cell(0, 8, f"Page {self.page_no()} | Generated by Lumina Assessment", align="C")

        def latin_safe(t):
            """Transliterates common unicode chars and strips the rest for latin-1 font support."""
            if not isinstance(t, str):
                t = str(t)
            reps = {
                '\u2018': "'", '\u2019': "'", '\u201c': '"', '\u201d': '"',
                '\u2013': "-", '\u2014': "-", '\u2026': "...", '\u00A0': " ",
                '\u2022': "-", '\u00B7': "-"
            }
            for k, v in reps.items():
                t = t.replace(k, v)
            return t.encode('latin-1', 'replace').decode('latin-1')

        def cell_nl(p, w, h, text, **kw):
            """Helper: cell with automatic newline."""
            p.cell(w, h, latin_safe(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT, **kw)

        def mcell(p, text):
            """Helper: multi_cell with safe defaults."""
            # Strip newlines that confuse fpdf within a single field
            safe = text.replace("\r", " ").replace("\n", " ")
            p.multi_cell(0, 5, latin_safe(safe), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf = LuminaPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        summary = schema.get("summary", {})
        ts  = schema.get("timestamp", "N/A")
        sid = schema.get("session_id", "N/A")

        # ── Title block ──
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(80, 50, 200)
        cell_nl(pdf, 0, 12, "Lumina Assessment", align="C")
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(80, 80, 80)
        cell_nl(pdf, 0, 7, f"Session: {sid}  |  Generated: {ts}", align="C")
        pdf.ln(6)

        # ── Summary box ──
        grade = summary.get("grade", "N/A")
        pdf.set_fill_color(240, 235, 255)
        pdf.set_draw_color(150, 100, 240)
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(60, 20, 160)
        summary_text = (
            f"Overall Grade: {grade}  |  "
            f"Score: {summary.get('total_score', 0)} / {summary.get('max_score', 0)}  |  "
            f"{summary.get('percentage', 0)}%"
        )
        cell_nl(pdf, 0, 10, summary_text, border=1, align="C", fill=True)
        pdf.ln(3)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        cell_nl(pdf, 0, 7,
                f"Total Questions: {summary.get('total_questions', 0)}  |  Correct: {summary.get('correct_count', 0)}")
        pdf.ln(4)

        # ── Per-type breakdown ──
        breakdown = summary.get("performance_breakdown", {})
        if breakdown:
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(60, 20, 160)
            cell_nl(pdf, 0, 8, "Performance by Question Type")
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            for qtype, stats in breakdown.items():
                tp  = round((stats["earned"] / stats["max"]) * 100) if stats["max"] else 0
                line = f"  {_trunc(qtype, 30)}: {stats['earned']}/{stats['max']} marks ({tp}%) - {stats['count']} question(s)"
                cell_nl(pdf, 0, 6, line)
            pdf.ln(4)

        pdf.set_draw_color(200, 200, 200)
        pdf.set_line_width(0.3)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)

        # ── Question breakdown ──
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(60, 20, 160)
        cell_nl(pdf, 0, 8, "Question-by-Question Breakdown")
        pdf.ln(2)

        for q in schema.get("questions", []):
            idx     = q["index"]
            qtype   = q["type"]
            score   = q["score"]
            max_s   = q["max_score"]
            is_corr = q["is_correct"]
            status  = "CORRECT" if is_corr else ("PARTIAL" if score > 0 else "INCORRECT")

            # Question header
            pdf.set_fill_color(245, 242, 255)
            pdf.set_draw_color(180, 150, 240)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(40, 10, 120)
            cell_nl(pdf, 0, 8,
                    f"Q{idx} [{qtype}]  -  {score}/{max_s} marks  -  {status}",
                    border=1, fill=True)

            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(30, 30, 30)
            mcell(pdf, f"Question: {_trunc(q['question'], 400)}")

            pdf.set_text_color(20, 100, 20)
            mcell(pdf, f"Correct Answer: {_trunc(q['correct_answer'], 300)}")

            user_color = (20, 100, 20) if is_corr else (160, 30, 30)
            pdf.set_text_color(*user_color)
            mcell(pdf, f"Your Answer: {_trunc(q['user_answer'], 300)}")

            if q.get("feedback"):
                pdf.set_text_color(80, 80, 80)
                mcell(pdf, f"Feedback: {_trunc(q['feedback'], 300)}")

            if q.get("strengths"):
                pdf.set_text_color(20, 120, 20)
                mcell(pdf, f"Strengths: {_trunc(q['strengths'], 200)}")

            if q.get("weaknesses"):
                pdf.set_text_color(160, 80, 0)
                mcell(pdf, f"Areas to Improve: {_trunc(q['weaknesses'], 200)}")

            if q.get("criteria_scores"):
                pdf.set_text_color(60, 60, 120)
                crit_text = "  |  ".join(
                    f"{k.replace('_', ' ').title()}: {v}"
                    for k, v in q["criteria_scores"].items()
                )
                mcell(pdf, f"Rubric: {_trunc(crit_text, 300)}")

            pdf.set_text_color(50, 50, 50)
            pdf.ln(3)

        buf = io.BytesIO()
        pdf.output(buf)
        buf.seek(0)
        return buf.getvalue()

    except Exception as e:
        logger.error(f"PDF generation failed: {e}", exc_info=True)
        return None


# ─────────────────────────────────────────────────────────────────────────────
# DOCX GENERATION
# ─────────────────────────────────────────────────────────────────────────────

def generate_docx_report(schema: dict) -> Optional[bytes]:
    """
    Generate a DOCX report from a normalized export schema.
    Returns raw bytes on success, None on failure.
    """
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()

        # Page margins
        for section in doc.sections:
            section.top_margin = Inches(0.75)
            section.bottom_margin = Inches(0.75)
            section.left_margin = Inches(0.9)
            section.right_margin = Inches(0.9)

        summary = schema.get("summary", {})
        ts = schema.get("timestamp", "N/A")
        sid = schema.get("session_id", "N/A")
        grade = summary.get("grade", "N/A")

        # ── Title ──
        title = doc.add_heading("Lumina Assessment — Evaluation Report", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title.runs[0].font.color.rgb = RGBColor(80, 50, 200)

        sub = doc.add_paragraph(f"Session: {sid}  |  Generated: {ts}")
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub.runs[0].font.size = Pt(10)
        sub.runs[0].font.color.rgb = RGBColor(100, 100, 100)

        doc.add_paragraph()  # spacer

        # ── Summary ──
        doc.add_heading("Summary", 1)
        tbl = doc.add_table(rows=1, cols=4)
        tbl.style = "Table Grid"
        hdr = tbl.rows[0].cells
        for cell, text in zip(hdr, ["Grade", "Score", "Percentage", "Correct"]):
            cell.text = text
            cell.paragraphs[0].runs[0].bold = True

        row = tbl.add_row().cells
        row[0].text = grade
        row[1].text = f"{summary.get('total_score', 0)} / {summary.get('max_score', 0)}"
        row[2].text = f"{summary.get('percentage', 0)}%"
        row[3].text = f"{summary.get('correct_count', 0)} / {summary.get('total_questions', 0)}"

        doc.add_paragraph()

        # ── Per-type breakdown ──
        breakdown = summary.get("performance_breakdown", {})
        if breakdown:
            doc.add_heading("Performance by Question Type", 2)
            for qtype, stats in breakdown.items():
                tp = round((stats["earned"] / stats["max"]) * 100) if stats["max"] else 0
                p = doc.add_paragraph(style="List Bullet")
                p.add_run(f"{qtype}: ").bold = True
                p.add_run(f"{stats['earned']}/{stats['max']} marks ({tp}%)  — {stats['count']} question(s)")

        doc.add_page_break()

        # ── Question breakdown ──
        doc.add_heading("Question-by-Question Breakdown", 1)

        for q in schema.get("questions", []):
            idx = q["index"]
            qtype = q["type"]
            score = q["score"]
            max_s = q["max_score"]
            is_corr = q["is_correct"]
            status = "CORRECT" if is_corr else ("PARTIAL" if score > 0 else "INCORRECT")

            # Question heading
            heading = doc.add_heading(level=3)
            run = heading.add_run(f"Q{idx} [{qtype}]  —  {score}/{max_s} marks  —  {status}")
            if is_corr:
                run.font.color.rgb = RGBColor(20, 140, 20)
            elif score > 0:
                run.font.color.rgb = RGBColor(180, 100, 0)
            else:
                run.font.color.rgb = RGBColor(180, 30, 30)

            def _add_line(label: str, text: str, bold_label=True, color=None):
                p = doc.add_paragraph()
                r_label = p.add_run(f"{label}: ")
                r_label.bold = bold_label
                r_text = p.add_run(_trunc(text, 500))
                if color:
                    r_text.font.color.rgb = color
                p.paragraph_format.space_after = Pt(2)

            _add_line("Question", q["question"])
            _add_line("Correct Answer", q["correct_answer"], color=RGBColor(20, 120, 20))
            _add_line("Your Answer", q["user_answer"],
                      color=RGBColor(20, 120, 20) if is_corr else RGBColor(160, 30, 30))

            if q.get("feedback"):
                _add_line("Feedback", q["feedback"])
            if q.get("strengths"):
                _add_line("Strengths", q["strengths"], color=RGBColor(20, 120, 20))
            if q.get("weaknesses"):
                _add_line("Areas to Improve", q["weaknesses"], color=RGBColor(160, 80, 0))
            if q.get("improvements"):
                _add_line("Improvements", q["improvements"])
            if q.get("criteria_scores"):
                crit_text = "  |  ".join(
                    f"{k.replace('_', ' ').title()}: {v}" for k, v in q["criteria_scores"].items()
                )
                _add_line("Rubric", crit_text, color=RGBColor(60, 60, 140))

            doc.add_paragraph()

        buf = io.BytesIO()
        doc.save(buf)
        buf.seek(0)
        return buf.getvalue()

    except Exception as e:
        logger.error(f"DOCX generation failed: {e}", exc_info=True)
        return None


# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _sanitize(text: str) -> str:
    """Strip control characters and limit length. Never trust raw LLM output."""
    if not isinstance(text, str):
        text = str(text)
    # Remove control chars except newline/tab
    text = re.sub(r"[^\x09\x0A\x20-\x7E\u00A0-\uFFFF]", "", text)
    return text.strip()


def _trunc(text: str, limit: int) -> str:
    """Truncate to limit with ellipsis to prevent overflow."""
    if not text:
        return ""
    return text[:limit] + ("..." if len(text) > limit else "")
